config/routes.rb
Rails.application.routes.draw do
  
  # 会員側のdeviseルーディング設定
  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }
  # 顧客側のdeviseルーディング設定
  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  
  root 'homes#top'
  get 'about' => 'homes#about', as: 'about'
  
  # 管理者側のルーティング設定
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end
  
  scope module: :user do
    get 'users/ranking' => 'users#ranking', as: 'ranking'
    resources :users, only: [:show, :edit, :update]
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  
  attachment :post_image
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :user_image, destroy: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    # @categories = Category.all
  end
  
  def about
  end
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mv">
      <nav class="navbar-expand-lg">
        <div class="container">
          <div class="col-4">
            <%= link_to root_path class:"navbar_brand" do %>
            
            <% end %>
          </div>
          <div class="navbar_nav ml-auto">
            <ul class="nav pull-right nav-pills">
              <% if admin_signed_in? %>
                <li><%= link_to "会員一覧", admin_user_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "ジャンル一覧", admin_category_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "投稿一覧", admin_post_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link btn btn-outline-dark  mx-2" %></li>
              <% elsif user_signed_in?%>
                <li><%= link_to "Home", root_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "About", about_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "マイページ", user_path(current_user.id), class:"nav-link btn btn-outline-dark  mx-2" %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link btn btn-outline-dark  mx-2" %></li>
                <div class="col text-right">
                  <p class="font-small">ようこそ、<%= current_user.first_name %>さん！</p>
                </div>
              <% else %>
                <li><%= link_to "Home", root_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "About", about_path, class:"nav-link btn btn-outline-dark mx-2" %></li>
                <li><%= link_to "新規登録", new_user_registration_path, class:"nav-link btn btn-outline-dark  mx-2" %></li>
                <li><%= link_to "ログイン", user_session_path, class:"nav-link btn btn-outline-dark  mx-2" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <%= yield %>
    <footer>
      <div class="p-3 text-white">
        <div class="container">
          <div class="row">
            <div class="mx-auto">
              <p>© 2021 Beers</p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>